import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "@/components/sections/Footer";
import GoTop from "@/components/buttons/GoTop";
import Navbar from "@/components/sections/Navbar";

import { Toaster } from "@/components/ui/sonner";

import GtagScripts from "@/components/GoogleTagsSrcipt";
import CookieBanner from "@/components/CookieBanner";
import GoogleConsentUpdater from "@/components/GoogleConsentUpdater";
import { ConsentProvider } from "@/hooks/useConsent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConsentProvider>
          <Navbar />
          {children}
          <CookieBanner />
          <GoogleConsentUpdater />
          <GtagScripts />
          <Footer />
          <Toaster />
          <GoTop />
        </ConsentProvider>
      </body>
    </html>
  );
}
